### ISSUE TITLE
Visualization bug with non identified keyword by pyplot

### ISSUE THREAD

**Issue by CuauSuarez** [pytorch/captum#1136] opened 2023-04-24 16:36 UTC
## 🐛 Bug

When using the `visualization_image_attr` function of the visualization library, it tries to set a grid parameter that is not recognized by `pyplot`. Specifically:

`plt_axis.grid(b=False)`

## To Reproduce

1. Run the `visualize_image_attr` function`

I get the following error:

    ValueError: keyword grid_b is not recognized; valid keywords are ['size', 'width', 'color', 'tickdir', 'pad', 'labelsize', 'labelcolor', 'zorder', 'gridOn', 'tick1On', 'tick2On', 'label1On', 'label2On', 'length', 'direction', 'left', 'bottom', 'right', 'top', 'labelleft', 'labelbottom', 'labelright', 'labeltop', 'labelrotation', 'grid_agg_filter', 'grid_alpha', 'grid_animated', 'grid_antialiased', 'grid_clip_box', 'grid_clip_on', 'grid_clip_path', 'grid_color', 'grid_dash_capstyle', 'grid_dash_joinstyle', 'grid_dashes', 'grid_data', 'grid_drawstyle', 'grid_figure', 'grid_fillstyle', 'grid_gapcolor', 'grid_gid', 'grid_in_layout', 'grid_label', 'grid_linestyle', 'grid_linewidth', 'grid_marker', 'grid_markeredgecolor', 'grid_markeredgewidth', 'grid_markerfacecolor', 'grid_markerfacecoloralt', 'grid_markersize', 'grid_markevery', 'grid_mouseover', 'grid_path_effects', 'grid_picker', 'grid_pickradius', 'grid_rasterized', 'grid_sketch_params', 'grid_snap', 'grid_solid_capstyle', 'grid_solid_joinstyle', 'grid_transform', 'grid_url', 'grid_visible', 'grid_xdata', 'grid_ydata', 'grid_zorder', 'grid_aa', 'grid_c', 'grid_ds', 'grid_ls', 'grid_lw', 'grid_mec', 'grid_mew', 'grid_mfc', 'grid_mfcalt', 'grid_ms']

## Environment
I am using Google Colab and installing captum as:

`pip install captum`

**Comment by kountaydwivedi** [comment] 2023-04-25 18:20
Yes, the issue is arising, maybe due to some library updates. The current solution that I am using is -- 
I am copying the code and making a custom function, wherein I am commenting the following line: `plt_axis.grid(b=False)`. 
:-}

**Comment by beew** [comment] 2023-04-28 08:45
The issue arises because of matplotlib update

I just encountered this tonight and I fixed it by editing site-packages/captum/attr/_utils/visualization.py and changed

line 250

from
```
 plt_axis.grid(b=False)
```
to
```
 plt_axis.grid(visible=False)
```

**Comment by lixi92** [comment] 2023-05-09 14:09
matplotlib 3.3.4 support this keyword

**Comment by cktse** [comment] 2023-06-06 04:46
FWIW this was a breaking API change introduced into matplotlib since 3.5.0:

The first parameter of Axes.grid and Axis.grid has been renamed to visible
The parameter was previously named b. This deprecation only matters if that parameter was passed using a keyword argument, e.g. grid(b=False).

https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.5.0.html#

**Comment by vivekmig** [comment] 2023-06-23 04:10
Apologies for the delay, this issue was fixed in #1118 to use the new visible parameter, and this fix will be available in the next release. Thanks for reporting this issue!

**Closed by vivekmig** 2023-06-23 04:10 UTC
