### ISSUE TITLE
Tutorial Page is down

### ISSUE THREAD

**Issue by tshrjn** [pytorch/captum#471] opened 2020-09-18 16:38 UTC
## 🐛 Bug

 The [tutorial website](https://captum.ai/tutorials/Titanic_Basic_Interpret) is down.

**Comment by orionr** [comment] 2020-09-18 16:50
@vivekmig, @NarineK and @jlin27 any thoughts? Thanks.

**Comment by vivekmig** [comment] 2020-09-18 19:54
This is fixed now, thanks for letting us know @tshrjn !

cc: @jlin27 The cause of this was a new version of nbconvert which broke the parse_tutorials script, fyi in case this affects other projects.

**Closed by vivekmig** 2020-09-18 19:54 UTC
