### ISSUE TITLE
how to get captum insights working

### ISSUE THREAD

**Issue by vainaijr** [pytorch/captum#225] opened 2020-01-04 12:12 UTC
it gives error after visualizer.render()
![Screenshot (205)](https://user-images.githubusercontent.com/43755000/71765341-cb134a80-2f36-11ea-81e5-0b4b2318da32.png)

and how do I get this saved image?
```
# show a screenshot if using notebook non-interactively
from IPython.display import Image
Image(filename='img/captum_insights.png')
```

**Comment by NarineK** [comment] 2020-01-04 19:57
Hi @vainaijr ! We are not fully supporting colab yet. Here is another issue related to that:
https://github.com/pytorch/captum/issues/116
cc: @edward-io , @J0Nreynolds

**Comment by edward-io** [comment] 2020-01-24 21:57
Closing out as its a dupe of #116. We're working on this and hope to get it working before the next release of Captum.

**Closed by edward-io** 2020-01-24 21:57 UTC
Labels: enhancement, question
