### ISSUE TITLE
threat-hunting with notebooks

### ISSUE THREAD

**Issue by dcshantelle** [pytorch/captum#1129] opened 2023-04-08 02:35 UTC
DeprecationWarning: Call to deprecated function (or staticmethod) display_timeseries_anomolies. (Will be removed in version 2.0.0. Please use display_timeseries_anomalies) -- Deprecated since version 1.7.0.
  timeseries_anomalies_plot = display_timeseries_anomolies(data=STL_df, y="TotalLogons", time_column='Date')
how do a fix this program

**Comment by vivekmig** [comment] 2023-06-23 13:38
Hi @dcshantelle , apologies for the late response! We could not find any usage of the function display_timeseries_anomolies in Captum, and it looks like this function may be from msticpy. Can you double check if this is related to Captum or another package? 

Closing this issue for now, feel free to create a new issue if the problem is related to Captum. Thanks!

**Closed by vivekmig** 2023-06-23 13:38 UTC
