### ISSUE TITLE
Captum LSTM sequences

### ISSUE THREAD

**Issue by rishkum** [pytorch/captum#737] opened 2021-08-23 15:37 UTC
## ❓ Questions and Help

I am fairly new to torch and Captum. Recently I created a LSTM model using pytorch and tried finding explanations for it.

After passing my torch LSTM model in `ig = IntegratedGradients(model)` I pass it in `ig_nt_attr_test = ig.attribute(sequence.unsqueeze(dim=0))` where sequence.unsqueeze(dim=0) is my test value sequence. The sequence tensor looks like this :
tensor([[[ 6.9921,  7.0432,  7.0107,  7.0262, -0.9805,  7.0031],
         [ 7.0379,  7.0099,  6.8940,  6.9066, -0.9718,  7.0262],
         [ 6.8056,  6.8896,  6.7307,  6.8102, -0.9680,  6.9066],
         [ 6.7991,  6.8671,  6.8414,  6.8457, -0.9847,  6.8102],
         [ 6.7824,  6.8553,  6.8159,  6.8576, -0.9810,  6.8457],
         [ 6.8891,  6.8886,  6.8777,  6.8393, -0.9831,  6.8576],
         [ 6.8595,  6.9471,  6.8739,  6.9384, -0.9825,  6.8393],
         [ 6.9382,  6.9337,  6.9336,  6.9163, -0.9848,  6.9384],
         [ 6.9226,  6.9363,  6.9277,  6.9222, -0.9875,  6.9163],
         [ 6.9004,  6.9090,  6.9102,  6.8845, -0.9854,  6.9222],
         [ 6.8923,  6.8869,  6.9042,  6.8818, -0.9868,  6.8845],
         [ 6.9053,  6.9412,  6.8923,  6.8553, -0.9814,  6.8818],
         [ 6.8842,  6.8880,  6.9048,  6.8693, -0.9869,  6.8553],
         [ 6.8918,  7.0133,  6.9216,  7.0329, -0.9805,  6.8693],
         [ 7.0419,  7.0343,  7.0536,  7.0442, -0.9840,  7.0329],
         [ 7.0187,  7.1284,  6.9558,  7.1532, -0.9722,  7.0442],
         [ 7.1099,  7.1547,  7.0982,  7.1030, -0.9751,  7.1532],
         [ 7.0867,  7.1031,  6.9385,  6.8963, -0.9767,  7.1030],
         [ 6.8291,  6.9568,  6.8488,  6.9147, -0.9766,  6.8963],
         [ 6.9593,  6.9837,  6.9727,  6.9951, -0.9838,  6.9147]]])

However this leads to the following error: 
```
--> 113         assert outputs[0].numel() == 1, (
    114             "Target not provided when necessary, cannot"
    115             " take gradient with respect to multiple outputs."

AttributeError: 'int' object has no attribute 'numel'
```
I am confused as to what to pass in attribute method instead of the test data.

**Comment by SaidaSaad** [comment] 2021-12-12 16:23
@rishkum Hi  
I would like to ask about one issue , 
I have pytorch model composed of Lstm layer followed by fc and another softmax layer.
I have some code same, takes sequence of length 341 and give one classes from {1,2,3} the model take batch of data of shape [16,341] and return vector of length 16. I am new to Capium , I am trying to use Intergrated Garidient but the following code did not work, Also I tried to use Deeplift and Saliency but nothing works for me , Is there is something wrong in the code? since you also have lstm pytorch model?

ig = IntegratedGradients(model)
test_input_tensor, targets = next(iter(testloader))
test_input_tensor =test_input_tensor.requires_grad_()
attr = ig.attribute(test_input_tensor, target = 0 , return_convergence_delta=False)
attr = attr.detach().numpy()

**Comment by bilalsal** [comment] 2022-01-07 19:47
2nd question duplicate of #816

**Closed by bilalsal** 2022-01-07 19:47 UTC
